In [1]:
class Employee:
    # Class variable to count the no.of employees
    employee_count = 0
    total_salary = 0

    def __init__(self, name, family, salary, department):
        # Initiate the instance variables
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department

        # Incrementing the total count of employees and total salary.
        Employee.employee_count += 1
        Employee.total_salary += salary

    @classmethod
    def average_salary(cls):
        # Method to calculate the average salary.
        if cls.employee_count == 0:
            return 0
        return cls.total_salary / cls.employee_count


# Fulltime Employee class inheriting from Employee
class FulltimeEmployee(Employee):
    fulltime_Employee_count = 0

    def __init__(self, name, family, salary, department):
        # Calling the constructor of the parent class
        super().__init__(name, family, salary, department)

        FulltimeEmployee.fulltime_Employee_count += 1


# Creating instances of Employee and FulltimeEmployee
emp1 = Employee("Keerthi", "Medarametla", 40000, "Team Lead")
emp2 = Employee("Arun", "Kodali", 50000, "Architect")
emp3 = FulltimeEmployee("Yousef", "Khan", 60000, "Development")
emp4 = FulltimeEmployee("Sania", "Mirza", 70000, "HR")
emp5 = FulltimeEmployee("Prabhas", "Uppalapati", 80000, "Manager")

# Print the average salary
print(f"Average Salary: {Employee.average_salary()}")

# Print the total number of employees
print(f"Total no.of Employees: {Employee.employee_count}")

# Print the total number of full time employees
print(f"Total no.of Full Time Employees: {FulltimeEmployee.fulltime_Employee_count}")


Average Salary: 60000.0
Total no.of Employees: 5
Total no.of Full Time Employees: 3


In [2]:
import numpy as np

# Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

# Reshape the array to 4 by 5
reshaped_array = random_vector.reshape(4, 5)

# Replace the max in each row by 0
# Using np.argmax to find the indices of the max in each row
max_indices = np.argmax(reshaped_array, axis=1)

# Creating a copy of the reshaped array to modify
modified_array = reshaped_array.copy()

# Replace the max values in each row with 0
modified_array[np.arange(modified_array.shape[0]), max_indices] = 0

# Output
print("Original 4x5 matrix:")
print(reshaped_array)

print("\nModified 4x5 matrix (max in each row replaced with 0):")
print(modified_array)


Original 4x5 matrix:
[[ 1.29274655 12.34049182  5.90999562  4.3292888  15.35169889]
 [12.26075616  6.1911705  10.63524894  2.74833962 17.5546925 ]
 [ 3.8188975  19.2446535  10.23262607 18.78420247  9.91417233]
 [15.36985423  3.03862736 10.58226121  5.28735581 11.93133356]]

Modified 4x5 matrix (max in each row replaced with 0):
[[ 1.29274655 12.34049182  5.90999562  4.3292888   0.        ]
 [12.26075616  6.1911705  10.63524894  2.74833962  0.        ]
 [ 3.8188975   0.         10.23262607 18.78420247  9.91417233]
 [ 0.          3.03862736 10.58226121  5.28735581 11.93133356]]
